---
- hosts: targetServer
  gather_facts: False
  become: true
  vars_files:
    - group_vars/aws-configuration.yml
  tasks:
    - include_role:
        name: aws-configuration
        tasks_from: absent
